[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["nodemailer"]

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/.well-known/assetlinks.json"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"

